name: fastcrypt
description: A high-performance, secure encryption library for Dart, leveraging the powerful **ChaCha20-Poly1305** algorithm.
version: 1.0.0
repository: https://github.com/jonataslaw/fastcrypt

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
